MVC5TestRepo/Models/SportStoreModels/Order.cs
using System.Collections.Generic;

namespace Models.SportStoreModels
{
    public class Order
    {
        public int Id { get; set; }
        public string Customer { get; set; }
        public decimal TotalCost { get; set; }
        public ICollection<OrderLine> Lines { get; set; }
    }
}

MVC5TestRepo/Controllers/PrepController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using Models.SportStoreModels;
using MVC5TestRepo.Models.SportStoreIdentity;
using MVC5TestRepo.Repositories.Implementation;
using MVC5TestRepo.Repositories.Interfaces;

namespace MVC5TestRepo.Controllers
{
    public class PrepController : Controller
    {
        private readonly ISportStoreRepository _repository;

        public PrepController()
        {
            _repository= new SportStoreRepository();
        }

        //
        // GET: /Prep/
        public ActionResult Index()
        {
            return View(_repository.Products);
        }

        [Authorize(Roles = "Administrators")]
        public async Task<ActionResult> DeleteProduct(int id)
        {
            await _repository.DeleteProductAsync(id);
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Administrators")]
        public async Task<ActionResult> SaveProduct(Product product)
        {
            await _repository.SaveProductAsync(product);
            return RedirectToAction("Index");
        }

        public ActionResult Orders()
        {
            return View(_repository.Orders);
        }

        public async Task<ActionResult> DeleteOrder(int id)
        {
            await _repository.DeleteOrderAsync(id);
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> SaveOrder(Order order)
        {
            await _repository.SaveOrderAsync(order);
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> SignIn()
        {
            IAuthenticationManager authMgr = HttpContext.GetOwinContext().Authentication;
            StoreUserManager userMrg = HttpContext.GetOwinContext().GetUserManager<StoreUserManager>();
            StoreUser user = await userMrg.FindAsync("Admin", "secret");
            authMgr.SignIn(await userMrg.CreateIdentityAsync(user,
            DefaultAuthenticationTypes.ApplicationCookie));
            return RedirectToAction("Index");
        }
        public ActionResult SignOut()
        {
            HttpContext.GetOwinContext().Authentication.SignOut();
            return RedirectToAction("Index");
        }
	}
}

MVC5TestRepo/Views/Prep/Index.cshtml
@model IEnumerable<Models.SportStoreModels.Product>
@{
    ViewBag.Title = "Products";
    Layout = "~/Views/Shared/_LayoutSportStore.cshtml";
}

<h2>Products</h2>

<div class="panel panel-primary">
    <div class="panel-heading">Products</div>
    <div class="panel panel-primary ">
        <a href="/prep/signin" class="btn btn-sm btn-primary">Sign In</a>
        <a href="/prep/signout" class="btn btn-sm btn-primary">Sign Out</a>
        User: @(HttpContext.Current.User.Identity.Name)
    </div>
    <table class="table table-striped">
        <tr><th>ID</th><th>Name</th><th>Category</th><th>Price</th></tr>
        @foreach (var product in Model)
        {
            <tr>
                <td>@product.Id</td>
                <td>@product.Name</td>
                <td>@product.Category</td>
                <td>@product.Description</td>
            </tr>
        }
    </table>
</div>

@using (Html.BeginForm("SaveProduct", "Prep"))
{
    <input type="hidden" name="Name" value="Zippy Running Shoes" />
    <input type="hidden" name="Category" value="Running" />
    <input type="hidden" name="Description" value="Set a new Record Time" />
    <input type="hidden" name="Price" value="159.99" />

    <button class="btn btn-primary" type="submit">Create</button>
    <a href="/prep/deleteproduct/2" class="btn btn-primary">Delete</a>
}

MVC5TestRepo/Views/Prep/Orders.cshtml
@using System.Globalization
@model IEnumerable<Models.SportStoreModels.Order>

@{
    ViewBag.Title = "Orders";
    Layout = "~/Views/Shared/_LayoutSportStore.cshtml";
}

<h2>Orders</h2>

<div class="panel panel-primary">
    <div class="panel-heading">
        Orders
    </div>
    <table class="table table-striped">
        <tr>
            <th>ID</th>
            <th>Customer</th>
            <th colspan="3"></th>
            <th>Total Cost</th>
        </tr>
        @foreach (var o in Model)
        {
            <tr>
                <td>@o.Id</td>
                <td>@o.Customer</td>
                <td colspan="3"></td>
                <td>@o.TotalCost.ToString("C", CultureInfo.GetCultureInfo("en-Gb"))</td>
            </tr>
            <tr>
                <th colspan="2"></th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Price</th>
                <th></th>
            </tr>
            foreach (var ol in o.Lines)
            {
                <tr>
                    <td colspan="2"></td>
                    <td>@ol.Product.Name</td>
                    <td>@ol.Count</td>
                    <td>@ol.Product.Price.ToString("C", CultureInfo.GetCultureInfo("en-Gb"))</td>
                    <td></td>
                </tr>
            }
        }
    </table>
</div>

@using (Html.BeginForm("SaveOrder", "Prep"))
{
    <input type="hidden" name="Customer" value="John Poet" />
    <input type="hidden" name="TotalCost" value="91" />
    <input type="hidden" name="lines[0].productid" value="6" />
    <input type="hidden" name="lines[0].count" value="1" />
    <input type="hidden" name="lines[1].productid" value="8" />
    <input type="hidden" name="lines[1].count" value="1" />
    <button class="btn btn-primary" type="submit">Create</button>
    <a href="/prep/deleteorder/2" class="btn btn-primary">Delete</a>
}    